import os






@celery.task(name='celery_mail_pdf.send')
def send(user):
    db_user = User.query.filter_by(username=user).first()
    if db_user:
        try:
            template = render_template('pdf_template.html',user=db_user, person=person, title=title)
            pdf = pdfkit.from_string(template, False)
            mail_sender = os.getenv('MAIL_USERNAME')
            msg = Message('Autogenerated Invoice', sender=mail_sender, recipients=[db_user.email]) #sender='keithnjagicodingtrials@gmail.com'
            msg.attach('result.pdf', 'application/pdf', pdf)
            mail.send(msg)
            return 'Mail sent successfully.'
        except Exception as e:
            return 'Could not send mail!!!'
    # else:
    #     break
    #     return 'No such user!!!'
        
